# Generated by Django 4.2.25 on 2025-10-13 11:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-population'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='trails_api__country_7ddc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='trails_api__is_capi_e3d8a0_idx',
        ),
        migrations.AlterField(
            model_name='city',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates', srid=4326),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='trails_api__name_17129a_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country'], name='trails_api__country_1686d9_idx'),
        ),
    ]
