# Generated by Django 4.2.25 on 2025-10-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_api', '0002_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='area_km2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
