# Generated by Django 4.2.25 on 2025-10-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0003_city_area_km2_city_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='city',
            new_name='trails_api__name_aa52d5_idx',
            old_name='trails_api__name_17129a_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='trails_api__country_c9aaf2_idx',
            old_name='trails_api__country_1686d9_idx',
        ),
        migrations.RenameIndex(
            model_name='city',
            new_name='trails_api__populat_98d358_idx',
            old_name='trails_api__populat_68da63_idx',
        ),
    ]
