# Generated by Django 4.2.25 on 2025-10-26 23:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0004_rename_trails_api__name_17129a_idx_trails_api__name_aa52d5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(db_index=True, max_length=200)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Trail length in kilometers', max_digits=6)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=10)),
                ('elevation_gain_m', models.IntegerField(help_text='Total elevation gain in meters')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(help_text='Trail start coordinates, longitude, latitude', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
