# Generated by Django 4.2.25 on 2025-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0005_trail_delete_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trail',
            options={'ordering': ['trail_name'], 'verbose_name': 'Trail', 'verbose_name_plural': 'Trails'},
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['county'], name='trails_api_county_idx'),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['difficulty'], name='trails_api_difficulty_idx'),
        ),
    ]
