# Generated by Django 4.2.25 on 2025-10-28 16:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0006_alter_trail_options_trail_trails_api_county_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='activity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trail',
            name='dogs_allowed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trail',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='nearest_town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trail',
            name='public_transport',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='trail_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
