# Generated by Django 4.2.25 on 2025-10-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0007_trail_activity_trail_dogs_allowed_trail_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=100),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, help_text='Trail length in kilometers', max_digits=20),
        ),
    ]
