# Generated by Django 4.2.25 on 2025-10-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0008_alter_trail_difficulty_alter_trail_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='parking_available',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
