# Generated by Django 4.2.25 on 2025-10-29 16:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0009_trail_parking_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Trail start coordinates, longitude, latitude', srid=4326),
        ),
    ]
