# Generated by Django 4.2.25 on 2025-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0011_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='town_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
