# Generated by Django 4.2.25 on 2025-10-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0012_town_area_town_population_town_town_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='dogs_allowed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
    ]
