# Generated by Django 4.2.25 on 2025-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
    ]
